version: '3'

services:
  db:
    image: postgres:13.1@sha256:c32f3f8364d79f71958c9ada74c43c2033d7e13d9d5fc21d3ba89322e6559c9d
    container_name: rust-graphql-sonic-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  sonic:
    image: valeriansaliou/sonic:v1.3.0@sha256:35cd79a23f74633fac7e0dc3a3b50a0bc644ce4935cb3d58c6417880d55941e8
    container_name: rust-graphql-sonic-sonic
    restart: always
    volumes:
      - sonic_data:/var/lib/sonic/store
      - ./sonic.cfg:/etc/sonic.cfg
    environment:
      SONIC_PASSWORD: ${SONIC_PASSWORD}
    ports:
      - '1491:1491'

  server:
    build: ./
    image: rust-graphql-sonic:latest
    container_name: server
    depends_on: &depends_on
      - db
      - sonic
    environment: &environment
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@rust-graphql-sonic-db:5432/${POSTGRES_DB}
      SONIC_PASSWORD: ${SONIC_PASSWORD}
      SONIC_URL: rust-graphql-sonic-sonic:1491
    ports:
      - '7878:7878'

  filler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: filler
    command: ['rust-graphql-sonic', '/tennis_atp']
    volumes:
      - ./tennis_atp:/tennis_atp
    container_name: filler
    depends_on: *depends_on
    environment: *environment

volumes:
  postgres_data: ~
  sonic_data: ~
